### PR TITLE
Arrows v1.0.0

### LINKED ISSUE #2: More human-readable macroexpansions
Moving over from https://github.com/cl-library-docs/common-lisp-libraries/issues/3

It might be worth to accomodate the needs of Lispers who don't enjoy arrows by making it possible to expand arrow macros into `let*` in the most naive way possible, so that the resulting macroexpansion can be normally read. For instance, let's consider a non-trivial example:

```lisp
(-<> 42
  (list <> <> <>)
  (cons 1 <>)
  (cons <> 2)
  (list <> :foo <>)
  (print <>))
```

The following currently expans into:

```lisp
(PRINT
 (LET ((#:R674
        (CONS
         (CONS 1
               (LET ((#:R673 42))
                 (LIST #:R673 #:R673 #:R673)))
         2)))
   (LIST #:R674 :FOO #:R674)))
```

The nested `let` is ugly and makes the macroexpansion very hard to grok.

I suggest that the above should expand into a variant of the following instead:

```lisp

(LET* ((#:VAR561 42)
       (#:VAR562 (LIST #:VAR561 #:VAR561 #:VAR561))
       (#:VAR563 (CONS 1 #:VAR563))
       (#:VAR564 (CONS #:VAR563 2))
       (#:VAR565 (LIST #:VAR564 :FOO #:VAR564)))
  (DECLARE (IGNORABLE #:VAR561 #:VAR562 #:VAR563 #:VAR564 #:VAR565))
  (PRINT #:VAR565))
```

This should be able to provide better readability for macroexpansions (importantly, `slime-macrostep`) and more debuggability for high debug settings since because the bound locals will be visible in the debugger. (One argument against this is that simple bindings, like the ones for variables number 561, 563, 564 up above, should be simplified into direct value passing, but IMO compilers are going to optimize those away anyway for low debug settings.)

### PR DESCRIPTION
**Pull request by phoe**
This commit overhauls Arrows and brings them to v1.0.0.

* The code is rewritten.
* All arrow macros now expand into `let*`.
* The arrows `some-<>`, `some-<>>`, `cond-<>`, `cond-<>>` are added.
* The Markdown documentation is updated.
* The documentation strings are updated.
* A Markdown tutorial for arrow macros is added.
* The test suite is expanded.

Fixes #2.

TODOs remaining:

* [ ] Implement `setf` expanders for arrows - see #4
* [ ] Finish the tutorial
* [ ] Add more examples

I'll request code review for this commit from `#lisp` and from the Lisp Discord.

Since the code was massively rewritten, it might be better to view the whole resulting repository at https://github.com/phoe-trash/arrows rather than try and view the diff for this change.

### CODE REVIEW

**Comment by phoe** [comment]
An issue highlighted by `fiddlerwoaroof` on `#lisp` is that `(->> (expensive) (or t))` no longer quickly returns `t` after this change. I don't yet know how to handle this.

**Comment by phoe** [comment]
Yes, there's a problem. My current implementation of arrows makes the assumption that each form passed to the threading macro is going to be evaluated; splicing such a form into a form with special evaluation rules, e.g. a macro, breaks this assumption.

And now that I think of it, this is un acceptable from an implementation of arrow macros. Clojure's arrows are syntactic sugar and therefore they are capable of operating even on data that makes no sense when it is evaluated; my rewrite breaks this assumption and therefore is not backwards compatible.

Because of this, sorry, I'll need to close this PR. I will publish my code as a separate system with different semantics.

**Comment by Harleqin** [comment]
Well, thanks for the research and effort anyway!

**Comment by digikar99** [comment]
Would it be a good sense to keep the default-optimization quality expansions as they are; but when `debug` is 3 (or some other optimization condition), the expansions are made in accordance with `binding-arrows`, since better debugging was the sole purpose of binding-arrows?

**Comment by phoe** [comment]
This is a bad idea.  Optimization qualities must not change the semantics of the program, and `(-> foo (defun (bar) (1+ bar)))` has different semantics under `arrows` and `binding-arrows`.

* In case of the former, it defines a function named `foo`;
* In case of the latter, it may signal an unbound variable error if `foo` is not globally bound, attempts to define a non-toplevel function with an unpredictable gensym name, and shall also signal an unused variable warning.

**Pull request closed without merging**
